### PR TITLE
fix: avoid adding margin for web

### LINKED ISSUE #1: Adding AlertsProvider adds vertical space
When I add `<AlertsProvider>`, it adds empty space below the application. Traced it to the `marginVertical: -300` in https://github.com/kuasha420/react-native-paper-alerts/blob/906de4cbd500fd4d1e71a43d0ddc839e811d25d8/src/provider.tsx#L474

Commenting it out seems to remove the weird space.

Is there a way to customize these styles or is this purely intended for internal use?

### PR DESCRIPTION
**Pull request by rchavik**
I found this seems to avoid the issue you mentioned with keyboard. Can you confirm?

Instead of adding marginVertical, we set minHeight from useWindowDimensions.

Closes #1

### CODE REVIEW

**Comment by rchavik** [comment]
| Original | Without `marginVertical` |  `marginVertical` removed + minHeight |
| -----------| ---------------------------------| ----------------------------------------------------|
| image | image | image

**Comment by kuasha420** [comment]
So close!

screenshot-2021-08-11_18 20 09 398

This is visible when the keyboard is being dismissed.

**Comment by rchavik** [comment]
Updated PR with 306b6f1af7331be7407519a463e4bcffc6e32f07, we keep the margin, but offset it in minHeight.

**Comment by rchavik** [comment]
> Updated PR with [306b6f1](https://github.com/kuasha420/react-native-paper-alerts/commit/306b6f1af7331be7407519a463e4bcffc6e32f07), we keep the margin, but offset it in minHeight.

nvm, please ignore. it seemed to fix the example program but didn't fix my use case

**Comment by kuasha420** [comment]
Fixed with #3

**Pull request closed without merging**
